# Generated by Django 5.0.7 on 2024-07-11 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('preparation_time', models.DurationField(default=datetime.timedelta(seconds=2520))),
                ('cooking_time', models.DurationField(default=datetime.timedelta(seconds=2520))),
                ('instructions', models.TextField()),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
            ],
        ),
    ]
